package zamours;

public class Reponse {
	String newLine = System.getProperty("line.separator");
	private String[][] tabReponse = new String[20][3];

	private int numQuizz;

	Reponse(int numQuizz) {
		this.numQuizz = numQuizz;
	}

	public void reponseQuizz(int numQuestion) {
		switch (numQuizz) {
		case 1:
			tabReponse[0][0] = "Salades et crudités, ça croustille mais c'est long à digérer";
			tabReponse[0][1] = "Lasagnes, pleins de couches à découvrir";
			tabReponse[0][2] = "Gigot d'agneau et purée, à l'ancienne mais indémodable";
			tabReponse[1][0] = "Salades et crudités, ça croustille mais c'est long à digérer";
			tabReponse[1][1] = "Lasagnes, pleins de couches à découvrir";
			tabReponse[1][2] = "Gigot d'agneau et purée, à l'ancienne mais indémodable";
			tabReponse[2][0] = "Georges Clooney, toute en urgence mais craquant";
			tabReponse[2][1] = "Austin Power, poilu, hilarant mais irrésistible";
			tabReponse[2][2] = "Kojak, chauve mais brillant et intelligent";
			tabReponse[3][0] = "Georges Clooney, toute en urgence mais craquant";
			tabReponse[3][1] = "Austin Power, poilu, hilarant mais irrésistible";
			tabReponse[3][2] = "Kojak, chauve mais brillant et intelligent";
			tabReponse[4][0] = "Plages, cocktails et cocotiers";
			tabReponse[4][1] = "Visite, découverte, sac à dos, camping";
			tabReponse[4][2] = "Plongé, vélo et canoë, histoire de se muscler";
			tabReponse[5][0] = "Plages, cocktails et cocotiers";
			tabReponse[5][1] = "Visite, découverte, sac à dos, camping";
			tabReponse[5][2] = "Plongé, vélo et canoë, histoire de se muscler";
			tabReponse[6][0] = "John Travolta, avec un déhanché du tonnerre";
			tabReponse[6][1] = "Columbo, à analyser le déhanché des autres filles";
			tabReponse[6][2] = "L'homme invisible, il partirait à la première occasion";
			tabReponse[7][0] = "John Travolta, avec un déhanché du tonnerre";
			tabReponse[7][1] = "Columbo, à analyser le déhanché des autres filles";
			tabReponse[7][2] = "L'homme invisible, tu partirais à la première occasion";
			tabReponse[8][0] = "9 semaines, pleines de surprises";
			tabReponse[8][1] = "Tatti Danielle, chiante mais attachante";
			tabReponse[8][2] = "Amely Poulain, nostalgique, rêveuse et imaginative";
			tabReponse[9][0] = "9 semaines, pleines de surprises";
			tabReponse[9][1] = "Tatti Danielle, chiante mais attanchante";
			tabReponse[9][2] = "Amely Poulain, nostalgique, rêveuse et imaginative";
			tabReponse[10][0] = "Brad Pitt, pour te prendre pour Jennifer Anniston";
			tabReponse[10][1] = "Sean Connery, pour être la nouvelle James Bond Girl";
			tabReponse[10][2] = "Gérard Jugnod, pour faire la choriste";
			tabReponse[11][0] = "Brad Pitt, pour se prendre pour Jennifer Anniston";
			tabReponse[11][1] = "Sean Connery, pour être la nouvelle James Bond Girl";
			tabReponse[11][2] = "Gérard Jugnod, pour faire la choriste";
			tabReponse[12][0] = "Ordonnée, elle classe même les épices par ordre alphabétique";
			tabReponse[12][1] = "Désordonnée, elle ne trouve jamais rien";
			tabReponse[12][2] = "Maniaque, elle a presque des TOCS";
			tabReponse[13][0] = "Ordonnée, tu classes mêmes les épices par ordre alphabétique";
			tabReponse[13][1] = "Désordonnée, tu ne retrouves jamais rien";
			tabReponse[13][2] = "Maniaque, tu as presque des TOCS";
			tabReponse[14][0] = "Bière, entre amis devant un match";
			tabReponse[14][1] = "Cocktails, avec toi au bord de l'eau";
			tabReponse[14][2] = "Whisky coca, en discothèque à matter";
			tabReponse[15][0] = "Bière, entre amis devant un match";
			tabReponse[15][1] = "Cocktails, avec elle au bord de l'eau";
			tabReponse[15][2] = "Whisky coca, en discothèque à matter";
			tabReponse[16][0] = "Belle, sympa mais déjà prise";
			tabReponse[16][1] = "Rigolote, intelligente et toujours la bienvenue";
			tabReponse[16][2] = "Pleine d'enthousiasme mais épuisante";
			tabReponse[17][0] = "Belle, sympa mais déjà prise";
			tabReponse[17][1] = "Rigolote, intelligente et toujours la bienvenue";
			tabReponse[17][2] = "Pleine d'enthousiasme mais épuisante";
			tabReponse[18][0] = "Un lapin, chaud et nourri pour pas cher";
			tabReponse[18][1] = "Un renard, à l'affut de la moindre occasion";
			tabReponse[18][2] = "Un paresseux, trop fatigué pour tenir l'aspirateur";
			tabReponse[19][0] = "Un lapin, chaud et nourri pour pas cher";
			tabReponse[19][1] = "Un renard, à l'affut de la moindre occasion";
			tabReponse[19][2] = "Un paresseux, trop fatigué pour tenir l'aspirateur";
			break;
		case 2:
			tabReponse[0][0] = "Chaud, genre « Rocco passe à l'attaque ».";
			tabReponse[0][1] = "Érotique, genre « Emmanuelle visite les Indes ».";
			tabReponse[0][2] = "Cucul la praline, genre « Oui oui fait des galipettes ».";
			tabReponse[1][0] = "Chaud, genre « Rocco passe à l'attaque ».";
			tabReponse[1][1] = "Érotique, genre « Emmanuelle visite les Indes ».";
			tabReponse[1][2] = "Cucul la praline, genre « Oui oui fait des galipettes ».";
			tabReponse[2][0] = "Une Ferrari, voyante, il adore ça.";
			tabReponse[2][1] = "Une Peugeot, simple, fonctionnelle.";
			tabReponse[2][2] = "Une Espace, grande famille et escapades familiales.";
			tabReponse[3][0] = "Une Ferrari, voyante, tu adores ça.";
			tabReponse[3][1] = "Une Peugeot, simple, fonctionnelle.";
			tabReponse[3][2] = "Une Espace, grande famille et escapades familiales.";
			tabReponse[4][0] = "Qui veut gagner des millions, l'intelligence toute en puissance.";
			tabReponse[4][1] = "Auto-Moto, essayer des voitures et conseiller les autres.";
			tabReponse[4][2] = "Les Z'amours, des questions idiotes mais il aime vous faire plaisir.";
			tabReponse[5][0] = "Qui veut gagner des millions, l'intelligence toute en puissance.";
			tabReponse[5][1] = "Auto-Motos, essayer des voitures et conseiller les autres.";
			tabReponse[5][2] = "Les Z'amours, des questions idiotes mais il aime vous faire plaisir.";
			tabReponse[6][0] = "\"Une de plus, je suis un vrai killer\".";
			tabReponse[6][1] = "\"Ha bah enfin une qui a du gout\".";
			tabReponse[6][2] = "\"Quoi j'ai la braguette ouverte c'est ça ?\"";
			tabReponse[7][0] = "\"Une de plus, je suis un vrai killer\".";
			tabReponse[7][1] = "\"Ha bah enfin une qui a du gout\".";
			tabReponse[7][2] = "\"Quoi j'ai la braguette ouverte c'est ça ?\".";
			tabReponse[8][0] = "Tu adores... \"Oh ma chérie, montre moi ton côté sauvage !\"";
			tabReponse[8][1] = "\"Toi, tu ne payes rien pour attendre !\"";
			tabReponse[8][2] = "\"Tu arrêtes tout... Non mais c'est quoi ces manières de sauvage !\"";
			tabReponse[9][0] = "Il adore... \"Oh ma chérie, montre moi ton côté sauvage !\"";
			tabReponse[9][1] = "\"Toi, tu ne payes rien pour attendre !\"";
			tabReponse[9][2] = "Il arrête tout... \"Non mais c'est quoi ces manières de sauvage !\"";
			tabReponse[10][0] = "A la bagatelle, vous ne pensiez qu'à ça.";
			tabReponse[10][1] = "A faire des projets.";
			tabReponse[10][2] = "Vous l'avez passée à vous prendre le bec.";
			tabReponse[11][0] = "A la bagatelle, vous ne pensiez qu'à ça.";
			tabReponse[11][1] = "A faire des projets.";
			tabReponse[11][2] = "Vous l'avez passée à vous prendre le bec.";
			tabReponse[12][0] = "\"Ne regarde pas le prix chérie, prends le caviar si tu en as envie\".";
			tabReponse[12][1] = "\"Ne regarde pas le prix chérie, prends le Big Mac si tu en as envie\".";
			tabReponse[12][2] = "\"Oups, j'ai encore oublié mon portefeuille\".";
			tabReponse[13][0] = "\"Ne regarde pas le prix chérie, prends le caviar si tu en as envie\".";
			tabReponse[13][1] = "\"Ne regarde pas le prix chérie, prends le Big Mac si tu en as envie\".";
			tabReponse[13][2] = "\"Oups, j'ai encore oublié mon portefeuille\".";
			tabReponse[14][0] = "\"Bien sûr, mon amour !\".";
			tabReponse[14][1] = "\"Tiens et moi, je vais attraper la grippe !\"";
			tabReponse[14][2] = "\"Que dal, si t'as froid, t'as qu'à courir !\"";
			tabReponse[15][0] = "\"Bien sûr, mon amour !\".";
			tabReponse[15][1] = "\"Tiens et moi, je vais attraper la grippe !\"";
			tabReponse[15][2] = "\"Que dal, si t'as froid, t'as qu'à courir !\"";
			tabReponse[16][0] = "\"Stresses pas chérie, s'ils ne sont pas content, ils ont qu'à doubler !\"";
			tabReponse[16][1] = "\"Passe-moi le volant, je vais la démarrer moi !\"";
			tabReponse[16][2] = "\"Enfin bon sens, démarre ! Tu ne vois pas qu'on se donne en spectacle non !\"";
			tabReponse[17][0] = "\"Stresse pas chérie, s'ils ne sont pas content, ils ont qu'à doubler !\"";
			tabReponse[17][1] = "\"Passe-moi le volant, je vais la démarrer moi !\"";
			tabReponse[17][2] = "\"Enfin bon sens, démarre ! Tu ne vois pas qu'on se donne en spectacle non !\"";
			tabReponse[18][0] = "Tu mets des lunettes pour ne pas être reconnue.";
			tabReponse[18][1] = "Tu compares les produits et demandes une démo";
			tabReponse[18][2] = "Tu le suis en gloussant comme une gamine";
			tabReponse[19][0] = "Elle met des lunettes pour ne pas être reconnue.";
			tabReponse[19][1] = "Elle compare les produits et demande une démo";
			tabReponse[19][2] = "Elle te suis en gloussant comme une gamine";
			break;
		case 3:
			tabReponse[0][0] = "C'est excellent et stimulant pour la vie de couple.";
			tabReponse[0][1] = "Ça ne concerne que les hommes qui les regardent plus ou\nmoins en cachette.";
			tabReponse[0][2] = "C'est nul et sans intérêt.";
			tabReponse[1][0] = "C'est excellent et stimulant pour la vie de couple.";
			tabReponse[1][1] = "Ça ne concerne que les hommes qui les regardent plus ou\nmoins en cachette.";
			tabReponse[1][2] = "C'est nul et sans intérêt.";
			tabReponse[2][0] = "Carrément indécent Que fait la police !.";
			tabReponse[2][1] = "Tout à fait charmant, c'est bien mieux que les géraniums.";
			tabReponse[2][2] = "Un peu décevant, pourquoi elle a gardé le string.";
			tabReponse[3][0] = "Carrément indécent Que fait la police !.";
			tabReponse[3][1] = "Tout à fait charmant, c'est bien mieux que les géraniums.";
			tabReponse[3][2] = "Un peu décevant, pourquoi elle a gardé le string.";
			tabReponse[4][0] = "Aujourd'hui vous pourriez lui dire, aujourd'hui on part\nen weekend thalasso !.";
			tabReponse[4][1] = "Allez, on se fait un bon resto !.";
			tabReponse[4][2] = "J'ai acheté du cassoulet, y'avait une promo !.";
			tabReponse[5][0] = "Aujourd'hui il pourrait te dire, aujourd'hui on part\nen weekend thalasso !.";
			tabReponse[5][1] = "Allez, on se fait un bon resto !.";
			tabReponse[5][2] = "J'ai acheté du cassoulet, y'avait une promo !.";
			tabReponse[6][0] = "En voiture.";
			tabReponse[6][1] = "Sous la couette.";
			tabReponse[6][2] = "Dans un magasin de vêtements.";
			tabReponse[7][0] = "En voiture.";
			tabReponse[7][1] = "Sous la couette.";
			tabReponse[7][2] = "Dans un magasin de vêtements.";
			tabReponse[8][0] = "tu l'envoies balader, ce n'est pas ton genre.";
			tabReponse[8][1] = "tu arraches tout en 3 secondes et tu lui saute dessus.";
			tabReponse[8][2] = "tu t'empêtres et finis par terre à tirer sur tes chaussettes.";
			tabReponse[9][0] = "Il vous envoie balader, ce n'est pas son genre.";
			tabReponse[9][1] = "Il arrache tout en 3 secondes et vous saute dessus.";
			tabReponse[9][2] = "Il s'empêtre et finit par terre à tirer sur ces chaussettes.";
			tabReponse[10][0] = "Ma pauvre t'es obligé de te cacher derrière tous ces produits.";
			tabReponse[10][1] = "Ho chérie, ton p'tit côté poupée, ça me chauffe à max !";
			tabReponse[10][2] = "Ho miss monde, laisses-moi la place !";
			tabReponse[11][0] = "Ma pauvre t'es obligé de te cacher derrière tous ces produits.";
			tabReponse[11][1] = "Ho chérie, ton p'tit côté poupée, ça me chauffe à max !";
			tabReponse[11][2] = "Ho miss monde, laisses-moi la place !";
			tabReponse[12][0] = "Crise de jalousie.";
			tabReponse[12][1] = "Crise de rire.";
			tabReponse[12][2] = "Crise d'autorité.";
			tabReponse[13][0] = "Crise de jalousie.";
			tabReponse[13][1] = "Crise de rire.";
			tabReponse[13][2] = "Crise d'autorité.";
			tabReponse[14][0] = "Faire les valises.";
			tabReponse[14][1] = "Faire l'amour.";
			tabReponse[14][2] = "Faire des visites.";
			tabReponse[15][0] = "Faire les valises.";
			tabReponse[15][1] = "Faire l'amour.";
			tabReponse[15][2] = "Faire des visites.";
			tabReponse[16][0] = "Elle est folle.";
			tabReponse[16][1] = "Elle est molle.";
			tabReponse[16][2] = "Quel sex-symbol.";
			tabReponse[17][0] = "Elle est folle.";
			tabReponse[17][1] = "Elle est molle.";
			tabReponse[17][2] = "Quel sex-symbol.";
			tabReponse[18][0] = "il ramasse tes affaires et les met dans le bac à linge.";
			tabReponse[18][1] = "Surexcité, il court pour te rejoindre dans la chambre.";
			tabReponse[18][2] = "Ce soir y'a match, il a d'autres occupations.";
			tabReponse[19][0] = "Tu ramasses ses affaires et les met dans le bac à linge.";
			tabReponse[19][1] = "Surexcité, tu cours pour la rejoindre dans la chambre.";
			tabReponse[19][2] = "Ce soir y'a match, tu as d'autres occupations.";
			break;
		}
	}

	public String afficheReponseQuizz(int q, int n) {
		reponseQuizz(numQuizz);
		return tabReponse[q][n];
	}

}